In [2]:
#pip list

In [3]:
import numpy as np

In [4]:
lst=[1,2,3,4,5]
arr=np.array(lst)
type(arr)


numpy.ndarray

In [5]:
arr.shape

(5,)

In [8]:
arr1=np.array([[1,2,3],[4,5,6]])

In [10]:
arr1.shape
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
arr1.dtype

dtype('int32')

In [12]:
np.array((1,2,3,4)).reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [18]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [22]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [26]:
##broadcast
5+ np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [30]:
np.eye(6)
np.eye(6).reshape(9,4)
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
print("uniform distribution")
np.random.rand(2,3)

uniform distribution


array([[0.14480048, 0.49725182, 0.14434685],
       [0.39302018, 0.56782199, 0.60004614]])

In [34]:
print("Random number following a Normal distribution with a mean=0 and std=1")
print(np.random.randn(5,3))

Random number following a Normal distribution with a mean=0 and std=1
[[ 0.70553281 -0.24670233 -1.05969482]
 [ 0.92643825 -0.08094164 -1.44443063]
 [ 0.00581451  0.17841492 -2.45817536]
 [ 0.38576635 -1.68672697  2.3635561 ]
 [ 0.54273655  0.48155898 -0.62741445]]


In [37]:
np.random.randint(1,100,(4,4))

array([[19, 22, 54, 71],
       [ 8, 75, 73, 85],
       [19,  2, 53, 50],
       [89, 91, 89, 22]])

In [42]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
## Slicing
arr[2:7]

array([2, 3, 4, 5, 6])

In [47]:
arr[-1]

10

In [48]:
arr[-1:7:-1]

array([10,  9,  8])

In [49]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [56]:
arr1=np.random.randint(2,100,20).reshape(5,4)
arr1

array([[ 5, 35, 65, 75],
       [68, 95, 46,  3],
       [70, 58, 51, 81],
       [ 2, 68, 72, 77],
       [33, 42, 65, 19]])

In [87]:
arr1[2, 0], arr1[3, 0], arr1[2, 3], arr1[3, 3]


(70, 2, 81, 77)

In [58]:
arr1[0:3,0:3]

array([[ 5, 35, 65],
       [68, 95, 46],
       [70, 58, 51]])

In [65]:
arr1[3:,1:]

array([[68, 72, 77],
       [42, 65, 19]])

In [88]:
arr1[2:4,1:3]

array([[58, 51],
       [68, 72]])

In [99]:
## Universal functions
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [90]:
arr1 + arr2

array([[183,  67,  86],
       [139,  52, 129],
       [ 70, 123,  55]])

In [91]:
arr1 * arr2

array([[8316, 1110, 1653],
       [4720,  672, 3888],
       [1125, 2376,  484]])

In [92]:
arr1 / arr2

array([[0.84848485, 1.23333333, 0.50877193],
       [1.3559322 , 1.16666667, 1.6875    ],
       [1.8       , 4.125     , 0.25      ]])

In [93]:
np.sqrt(arr1)

array([[9.16515139, 6.08276253, 5.38516481],
       [8.94427191, 5.29150262, 9.        ],
       [6.70820393, 9.94987437, 3.31662479]])

In [94]:
np.exp(arr2)

array([[9.88903032e+42, 1.06864746e+13, 5.68572000e+24],
       [4.20121040e+25, 2.64891221e+10, 7.01673591e+20],
       [7.20048993e+10, 2.64891221e+10, 1.28516001e+19]])

In [95]:
np.log10(arr1)

array([[1.92427929, 1.56820172, 1.462398  ],
       [1.90308999, 1.44715803, 1.90848502],
       [1.65321251, 1.99563519, 1.04139269]])

In [96]:
arr1=np.arange(1,11)

In [98]:
arr1[2:]=1000
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [100]:
np.matmul(arr1,arr2)

array([[ 4676,  5036,  5887],
       [10246, 10714,  7770],
       [ 8818, 10574,  9776]])

In [101]:
np.dot(arr1,arr2)

array([[ 4676,  5036,  5887],
       [10246, 10714,  7770],
       [ 8818, 10574,  9776]])